// <auto-generated />
using System;
using Assassins.DataAccess.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Assassins.DataAccess.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20190623003629_initial-migration-5")]
    partial class initialmigration5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Assassins.DataModels.Actions.Action", b =>
                {
                    b.Property<int>("AaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<int>("action_type_id");

                    b.Property<long?>("campaign_insight_id");

                    b.Property<double>("value");

                    b.HasKey("AaId");

                    b.HasIndex("action_type_id");

                    b.HasIndex("campaign_insight_id");

                    b.ToTable("Actions");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Action");
                });

            modelBuilder.Entity("Assassins.DataModels.Actions.ActionType", b =>
                {
                    b.Property<int>("AaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("action_type");

                    b.HasKey("AaId");

                    b.ToTable("ActionTypes");
                });

            modelBuilder.Entity("Assassins.DataModels.AdAccounts.AdAccount", b =>
                {
                    b.Property<long>("account_id");

                    b.Property<long>("AppUserDataSyncId");

                    b.Property<int>("AppUserId");

                    b.Property<DateTime>("DateRecorded");

                    b.Property<int>("account_status");

                    b.Property<double>("age");

                    b.Property<long>("amount_spent");

                    b.Property<double>("balance");

                    b.Property<string>("business_city");

                    b.Property<string>("business_country_code");

                    b.Property<long?>("business_id");

                    b.Property<string>("business_name");

                    b.Property<string>("business_street");

                    b.Property<string>("business_street2");

                    b.Property<DateTime>("created_time");

                    b.Property<string>("currency");

                    b.Property<int>("disable_reason");

                    b.Property<long?>("end_advertiser");

                    b.Property<string>("end_advertiser_name");

                    b.Property<int>("fb_entity");

                    b.Property<int>("min_campaign_group_spend_cap");

                    b.Property<int>("min_daily_budget");

                    b.Property<string>("name");

                    b.Property<long>("owner");

                    b.Property<int>("spend_cap");

                    b.Property<int>("timezone_id");

                    b.Property<string>("timezone_name");

                    b.Property<int>("timezone_offset_hours_utc");

                    b.HasKey("account_id");

                    b.HasIndex("AppUserDataSyncId");

                    b.HasIndex("AppUserId");

                    b.HasIndex("business_id");

                    b.ToTable("AdAccounts");
                });

            modelBuilder.Entity("Assassins.DataModels.AdAccounts.Business", b =>
                {
                    b.Property<long>("id");

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.ToTable("Business");
                });

            modelBuilder.Entity("Assassins.DataModels.AdAccounts._AdAccountHistoryItem", b =>
                {
                    b.Property<long>("AppUserDataSyncId");

                    b.Property<long>("account_id");

                    b.Property<int>("AppUserId");

                    b.Property<DateTime>("DateRecorded");

                    b.Property<int>("account_status");

                    b.Property<double>("age");

                    b.Property<long>("amount_spent");

                    b.Property<double>("balance");

                    b.Property<string>("business_city");

                    b.Property<string>("business_country_code");

                    b.Property<long?>("business_id");

                    b.Property<string>("business_name");

                    b.Property<string>("business_street");

                    b.Property<string>("business_street2");

                    b.Property<long?>("businessid");

                    b.Property<DateTime>("created_time");

                    b.Property<string>("currency");

                    b.Property<int>("disable_reason");

                    b.Property<long?>("end_advertiser");

                    b.Property<string>("end_advertiser_name");

                    b.Property<int>("fb_entity");

                    b.Property<int>("min_campaign_group_spend_cap");

                    b.Property<int>("min_daily_budget");

                    b.Property<string>("name");

                    b.Property<long>("owner");

                    b.Property<int>("spend_cap");

                    b.Property<int>("timezone_id");

                    b.Property<string>("timezone_name");

                    b.Property<int>("timezone_offset_hours_utc");

                    b.HasKey("AppUserDataSyncId", "account_id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("businessid");

                    b.ToTable("_AdAccountHistory");
                });

            modelBuilder.Entity("Assassins.DataModels.AdImages.AdImage", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("AppUserDataSyncId");

                    b.Property<DateTime>("DateRecorded");

                    b.Property<long>("account_id");

                    b.Property<DateTime>("created_time");

                    b.Property<string>("hash");

                    b.Property<int>("height");

                    b.Property<bool>("is_associated_creatives_in_adgroups");

                    b.Property<string>("name");

                    b.Property<int>("original_height");

                    b.Property<int>("original_width");

                    b.Property<string>("permalink_url");

                    b.Property<string>("status");

                    b.Property<DateTime>("update_time");

                    b.Property<string>("url");

                    b.Property<string>("url_128");

                    b.Property<int>("width");

                    b.HasKey("id");

                    b.HasIndex("AppUserDataSyncId");

                    b.ToTable("AdImages");
                });

            modelBuilder.Entity("Assassins.DataModels.AdImages._AdImageHistoryItem", b =>
                {
                    b.Property<long>("AppUserDataSyncId");

                    b.Property<string>("id");

                    b.Property<DateTime>("DateRecorded");

                    b.Property<long>("account_id");

                    b.Property<DateTime>("created_time");

                    b.Property<string>("hash");

                    b.Property<int>("height");

                    b.Property<bool>("is_associated_creatives_in_adgroups");

                    b.Property<string>("name");

                    b.Property<int>("original_height");

                    b.Property<int>("original_width");

                    b.Property<string>("permalink_url");

                    b.Property<string>("status");

                    b.Property<DateTime>("update_time");

                    b.Property<string>("url");

                    b.Property<string>("url_128");

                    b.Property<int>("width");

                    b.HasKey("AppUserDataSyncId", "id");

                    b.ToTable("_AdImageHistory");
                });

            modelBuilder.Entity("Assassins.DataModels.AdSets.AdSet", b =>
                {
                    b.Property<long>("id");

                    b.Property<long>("AppUserDataSyncId");

                    b.Property<DateTime>("DateRecorded");

                    b.Property<long>("account_id");

                    b.Property<string>("bid_strategy");

                    b.Property<string>("billing_event");

                    b.Property<int>("budget_remaining");

                    b.Property<long>("campaign_id");

                    b.Property<string>("configured_status");

                    b.Property<DateTime>("created_time");

                    b.Property<int>("daily_budget");

                    b.Property<string>("destination_type");

                    b.Property<string>("effective_status");

                    b.Property<DateTime>("end_time");

                    b.Property<bool>("is_dynamic_creative");

                    b.Property<int>("lifetime_budget");

                    b.Property<int>("lifetime_imps");

                    b.Property<string>("name");

                    b.Property<string>("optimization_goal");

                    b.Property<string>("optimization_sub_event");

                    b.Property<bool>("recurring_budget_semantics");

                    b.Property<long>("source_adset_id");

                    b.Property<DateTime>("start_time");

                    b.Property<string>("status");

                    b.Property<DateTime>("updated_time");

                    b.Property<bool>("use_new_app_click");

                    b.HasKey("id");

                    b.HasIndex("AppUserDataSyncId");

                    b.HasIndex("account_id");

                    b.HasIndex("campaign_id");

                    b.ToTable("AdSets");
                });

            modelBuilder.Entity("Assassins.DataModels.AdSets.Geolocation", b =>
                {
                    b.Property<long>("adset_id");

                    b.Property<long>("AppUserDataSyncId");

                    b.Property<DateTime>("DateRecorded");

                    b.Property<string>("location_types");

                    b.HasKey("adset_id");

                    b.HasIndex("AppUserDataSyncId");

                    b.ToTable("Geolocations");
                });

            modelBuilder.Entity("Assassins.DataModels.AdSets.GeolocationRegionMap", b =>
                {
                    b.Property<long>("adset_id");

                    b.Property<int>("key");

                    b.Property<long>("AppUserDataSyncId");

                    b.Property<DateTime>("DateRecorded");

                    b.HasKey("adset_id", "key");

                    b.HasIndex("AppUserDataSyncId");

                    b.HasIndex("key");

                    b.ToTable("GeolocationRegionMaps");
                });

            modelBuilder.Entity("Assassins.DataModels.AdSets.Region", b =>
                {
                    b.Property<int>("key");

                    b.Property<string>("country");

                    b.Property<string>("name");

                    b.HasKey("key");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("Assassins.DataModels.AdSets.Targeting", b =>
                {
                    b.Property<long>("adset_id");

                    b.Property<long>("AppUserDataSyncId");

                    b.Property<DateTime>("DateRecorded");

                    b.Property<int>("age_max");

                    b.Property<int>("age_min");

                    b.Property<string>("device_platforms");

                    b.Property<string>("facebook_positions");

                    b.Property<string>("instagram_positions");

                    b.Property<string>("publisher_platforms");

                    b.HasKey("adset_id");

                    b.HasIndex("AppUserDataSyncId");

                    b.ToTable("Targeting");
                });

            modelBuilder.Entity("Assassins.DataModels.AdSets._AdSetHistoryItem", b =>
                {
                    b.Property<long>("AppUserDataSyncId");

                    b.Property<long>("id");

                    b.Property<DateTime>("DateRecorded");

                    b.Property<long>("account_id");

                    b.Property<string>("bid_strategy");

                    b.Property<string>("billing_event");

                    b.Property<int>("budget_remaining");

                    b.Property<long>("campaign_id");

                    b.Property<string>("configured_status");

                    b.Property<DateTime>("created_time");

                    b.Property<int>("daily_budget");

                    b.Property<string>("destination_type");

                    b.Property<string>("effective_status");

                    b.Property<DateTime>("end_time");

                    b.Property<bool>("is_dynamic_creative");

                    b.Property<int>("lifetime_budget");

                    b.Property<int>("lifetime_imps");

                    b.Property<string>("name");

                    b.Property<string>("optimization_goal");

                    b.Property<string>("optimization_sub_event");

                    b.Property<bool>("recurring_budget_semantics");

                    b.Property<long>("source_adset_id");

                    b.Property<DateTime>("start_time");

                    b.Property<string>("status");

                    b.Property<DateTime>("updated_time");

                    b.Property<bool>("use_new_app_click");

                    b.HasKey("AppUserDataSyncId", "id");

                    b.ToTable("_AdSetHistory");
                });

            modelBuilder.Entity("Assassins.DataModels.AdSets._GeolocationHistoryItem", b =>
                {
                    b.Property<long>("AppUserDataSyncId");

                    b.Property<long>("adset_id");

                    b.Property<DateTime>("DateRecorded");

                    b.Property<string>("location_types");

                    b.HasKey("AppUserDataSyncId", "adset_id");

                    b.ToTable("_GeolocationHistory");
                });

            modelBuilder.Entity("Assassins.DataModels.AdSets._GeolocationRegionMapHistoryItem", b =>
                {
                    b.Property<long>("AppUserDataSyncId");

                    b.Property<long>("adset_id");

                    b.Property<int>("key");

                    b.Property<DateTime>("DateRecorded");

                    b.HasKey("AppUserDataSyncId", "adset_id", "key");

                    b.ToTable("_GeolocationRegionMapHistory");
                });

            modelBuilder.Entity("Assassins.DataModels.AdSets._TargetingHistoryItem", b =>
                {
                    b.Property<long>("AppUserDataSyncId");

                    b.Property<long>("adset_id");

                    b.Property<DateTime>("DateRecorded");

                    b.Property<int>("age_max");

                    b.Property<int>("age_min");

                    b.Property<string>("device_platforms");

                    b.Property<string>("facebook_positions");

                    b.Property<string>("instagram_positions");

                    b.Property<string>("publisher_platforms");

                    b.HasKey("AppUserDataSyncId", "adset_id");

                    b.ToTable("_TargetingHistory");
                });

            modelBuilder.Entity("Assassins.DataModels.Ads.Ad", b =>
                {
                    b.Property<long>("id");

                    b.Property<long>("AppUserDataSyncId");

                    b.Property<DateTime>("DateRecorded");

                    b.Property<long>("account_id");

                    b.Property<long>("adset_id");

                    b.Property<string>("bid_type");

                    b.Property<long>("campaign_id");

                    b.Property<string>("configured_status");

                    b.Property<DateTime>("created_time");

                    b.Property<string>("effective_status");

                    b.Property<long>("last_updated_by_app_id");

                    b.Property<string>("name");

                    b.Property<long>("source_ad_id");

                    b.Property<string>("status");

                    b.Property<DateTime>("updated_time");

                    b.HasKey("id");

                    b.HasIndex("AppUserDataSyncId");

                    b.HasIndex("account_id");

                    b.HasIndex("adset_id");

                    b.HasIndex("campaign_id");

                    b.ToTable("Ads");
                });

            modelBuilder.Entity("Assassins.DataModels.Ads._AdHistoryItem", b =>
                {
                    b.Property<long>("AppUserDataSyncId");

                    b.Property<long>("id");

                    b.Property<DateTime>("DateRecorded");

                    b.Property<long>("account_id");

                    b.Property<long>("adset_id");

                    b.Property<string>("bid_type");

                    b.Property<long>("campaign_id");

                    b.Property<string>("configured_status");

                    b.Property<DateTime>("created_time");

                    b.Property<string>("effective_status");

                    b.Property<long>("last_updated_by_app_id");

                    b.Property<string>("name");

                    b.Property<long>("source_ad_id");

                    b.Property<string>("status");

                    b.Property<DateTime>("updated_time");

                    b.HasKey("AppUserDataSyncId", "id");

                    b.ToTable("_AdHistory");
                });

            modelBuilder.Entity("Assassins.DataModels.AppUsers.AppRole", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("RoleId");

                    b.ToTable("AppRoles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Name = "Administrator"
                        },
                        new
                        {
                            RoleId = 2,
                            Name = "Assassins Club Free"
                        },
                        new
                        {
                            RoleId = 3,
                            Name = "Assassins Club Premium"
                        },
                        new
                        {
                            RoleId = 4,
                            Name = "Assassins Club Platinum"
                        });
                });

            modelBuilder.Entity("Assassins.DataModels.AppUsers.AppUser", b =>
                {
                    b.Property<int>("AppUserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdAssassinId");

                    b.Property<string>("AvatarUrl");

                    b.Property<string>("CreatedBy");

                    b.Property<int>("CreatedById");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Email");

                    b.Property<string>("ExternalId");

                    b.Property<string>("FirstName");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsSuspended");

                    b.Property<string>("LastName");

                    b.Property<string>("ModifiedBy");

                    b.Property<int>("ModifiedById");

                    b.Property<DateTime>("ModifiedOn");

                    b.Property<long?>("id");

                    b.HasKey("AppUserId");

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            AppUserId = 1,
                            AvatarUrl = "http://free-icon-rainbow.com/i/icon_04062/icon_040629_64.png",
                            CreatedBy = "joe.jordan@assassinsclub.com",
                            CreatedById = 2,
                            CreatedOn = new DateTime(1980, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "system@assassinsclub.com",
                            ExternalId = "8BNz8FqTVGVjYyXudC6DSZkpiws1",
                            FirstName = "System",
                            IsDeleted = false,
                            IsSuspended = false,
                            LastName = "Bot",
                            ModifiedBy = "joe.jordan@assassinsclub.com",
                            ModifiedById = 2,
                            ModifiedOn = new DateTime(1980, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppUserId = 2,
                            AvatarUrl = "https://i0.wp.com/cdn.auth0.com/avatars/dj.png?ssl=1",
                            CreatedBy = "system@assassinsclub.com",
                            CreatedById = 1,
                            CreatedOn = new DateTime(1980, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "joe.jordan@outlook.com",
                            ExternalId = "lv9iYbUYKdRQ0i700sVt9ZjVFps1",
                            FirstName = "Joe",
                            IsDeleted = false,
                            IsSuspended = false,
                            LastName = "Jordan",
                            ModifiedBy = "system@assassinsclub.com",
                            ModifiedById = 1,
                            ModifiedOn = new DateTime(1980, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppUserId = 3,
                            AvatarUrl = "https://i0.wp.com/cdn.auth0.com/avatars/jj.png?ssl=1",
                            CreatedBy = "system@assassinsclub.com",
                            CreatedById = 1,
                            CreatedOn = new DateTime(1980, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "joe.jordan25@gmail.com",
                            ExternalId = "x1EZhRH3tVfwTEsE2f2nHJce4yy2",
                            FirstName = "Joe",
                            IsDeleted = false,
                            IsSuspended = false,
                            LastName = "Jordan",
                            ModifiedBy = "system@assassinsclub.com",
                            ModifiedById = 1,
                            ModifiedOn = new DateTime(1980, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Assassins.DataModels.AppUsers.AppUserDataSync", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AdAccountsCompleted");

                    b.Property<bool>("AdImagesCompleted");

                    b.Property<bool>("AdInsightsCompleted");

                    b.Property<bool>("AdSetsCompleted");

                    b.Property<bool>("AdsCompleted");

                    b.Property<int>("AppUserId");

                    b.Property<bool>("CampaignsCompleted");

                    b.Property<bool>("CreativesCompleted");

                    b.Property<DateTime?>("EndTime");

                    b.Property<bool>("LeadFormsCompleted");

                    b.Property<DateTime>("StartTime");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("AppUserDataSyncs");
                });

            modelBuilder.Entity("Assassins.DataModels.AppUsers.AppUserRole", b =>
                {
                    b.Property<int>("AppUserId");

                    b.Property<int>("RoleId");

                    b.HasKey("AppUserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AppUserRole");

                    b.HasData(
                        new
                        {
                            AppUserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            AppUserId = 2,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("Assassins.DataModels.Campaigns.Campaign", b =>
                {
                    b.Property<long>("id");

                    b.Property<long>("AppUserDataSyncId");

                    b.Property<int>("AppUserId");

                    b.Property<DateTime>("DateRecorded");

                    b.Property<long>("account_id");

                    b.Property<bool>("budget_rebalance_flag");

                    b.Property<int>("budget_remaining");

                    b.Property<string>("buying_type");

                    b.Property<bool>("can_create_brand_lift_study");

                    b.Property<bool>("can_use_spend_cap");

                    b.Property<string>("configured_status");

                    b.Property<DateTime>("created_time");

                    b.Property<string>("effective_status");

                    b.Property<string>("name");

                    b.Property<string>("objective");

                    b.Property<long?>("source_campaign_id");

                    b.Property<DateTime>("start_time");

                    b.Property<string>("status");

                    b.Property<DateTime?>("stop_time");

                    b.Property<DateTime?>("updated_time");

                    b.HasKey("id");

                    b.HasIndex("AppUserDataSyncId");

                    b.HasIndex("AppUserId");

                    b.HasIndex("account_id");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("Assassins.DataModels.Campaigns.CampaignInsight", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("buying_type");

                    b.Property<long>("campaign_id");

                    b.Property<int>("clicks");

                    b.Property<double>("cost_per_inline_link_click");

                    b.Property<double>("cost_per_inline_post_engagement");

                    b.Property<double>("cost_per_unique_click");

                    b.Property<double>("cost_per_unique_inline_link_click");

                    b.Property<double>("cpc");

                    b.Property<double>("cpm");

                    b.Property<double>("cpp");

                    b.Property<double>("ctr");

                    b.Property<DateTime>("date_start");

                    b.Property<DateTime>("date_stop");

                    b.Property<double>("frequency");

                    b.Property<long>("impressions");

                    b.Property<double>("inline_link_click_ctr");

                    b.Property<long>("inline_link_clicks");

                    b.Property<long>("inline_post_engagement");

                    b.Property<long>("instant_experience_clicks_to_open");

                    b.Property<long>("instant_experience_clicks_to_start");

                    b.Property<long>("instant_experience_outbound_clicks");

                    b.Property<string>("objective");

                    b.Property<long>("reach");

                    b.Property<double>("social_spend");

                    b.Property<double>("spend");

                    b.Property<long>("unique_clicks");

                    b.Property<double>("unique_ctr");

                    b.Property<double>("unique_inline_link_click_ctr");

                    b.Property<long>("unique_inline_link_clicks");

                    b.Property<double>("unique_link_clicks_ctr");

                    b.HasKey("id");

                    b.HasIndex("campaign_id");

                    b.ToTable("CampaignInsights");
                });

            modelBuilder.Entity("Assassins.DataModels.Campaigns._CampaignHistoryItem", b =>
                {
                    b.Property<long>("AppUserDataSyncId");

                    b.Property<long>("id");

                    b.Property<int>("AppUserId");

                    b.Property<DateTime>("DateRecorded");

                    b.Property<long>("account_id");

                    b.Property<bool>("budget_rebalance_flag");

                    b.Property<int>("budget_remaining");

                    b.Property<string>("buying_type");

                    b.Property<bool>("can_create_brand_lift_study");

                    b.Property<bool>("can_use_spend_cap");

                    b.Property<string>("configured_status");

                    b.Property<DateTime>("created_time");

                    b.Property<string>("effective_status");

                    b.Property<string>("name");

                    b.Property<string>("objective");

                    b.Property<long?>("source_campaign_id");

                    b.Property<DateTime>("start_time");

                    b.Property<string>("status");

                    b.Property<DateTime?>("stop_time");

                    b.Property<DateTime?>("updated_time");

                    b.HasKey("AppUserDataSyncId", "id");

                    b.HasIndex("AppUserId");

                    b.ToTable("_CampaignHistory");
                });

            modelBuilder.Entity("Assassins.DataModels.Creatives.AdCreative", b =>
                {
                    b.Property<long>("id");

                    b.Property<string>("AdImageid");

                    b.Property<long>("AppUserDataSyncId");

                    b.Property<DateTime>("DateRecorded");

                    b.Property<long>("account_id");

                    b.Property<string>("adimage_id");

                    b.Property<string>("body");

                    b.Property<string>("call_to_action_type");

                    b.Property<long?>("effective_instagram_story_id");

                    b.Property<string>("effective_object_story_id");

                    b.Property<string>("image_hash");

                    b.Property<string>("image_url");

                    b.Property<long?>("instagram_actor_id");

                    b.Property<string>("instagram_permalink_url");

                    b.Property<long?>("instagram_story_id");

                    b.Property<long?>("link_og_id");

                    b.Property<string>("link_url");

                    b.Property<string>("messenger_sponsored_message");

                    b.Property<string>("name");

                    b.Property<long?>("object_id");

                    b.Property<string>("object_story_id");

                    b.Property<string>("object_type");

                    b.Property<string>("object_url");

                    b.Property<string>("status");

                    b.Property<string>("template_url");

                    b.Property<string>("thumbnail_url");

                    b.Property<string>("title");

                    b.Property<string>("url_tags");

                    b.Property<long?>("video_id");

                    b.HasKey("id");

                    b.HasIndex("AdImageid");

                    b.HasIndex("AppUserDataSyncId");

                    b.HasIndex("account_id");

                    b.ToTable("AdCreatives");
                });

            modelBuilder.Entity("Assassins.DataModels.Creatives._AdCreativeHistoryItem", b =>
                {
                    b.Property<long>("AppUserDataSyncId");

                    b.Property<long>("id");

                    b.Property<DateTime>("DateRecorded");

                    b.Property<long>("account_id");

                    b.Property<string>("adimage_id");

                    b.Property<string>("body");

                    b.Property<string>("call_to_action_type");

                    b.Property<long?>("effective_instagram_story_id");

                    b.Property<string>("effective_object_story_id");

                    b.Property<string>("image_hash");

                    b.Property<string>("image_url");

                    b.Property<long?>("instagram_actor_id");

                    b.Property<string>("instagram_permalink_url");

                    b.Property<long?>("instagram_story_id");

                    b.Property<long?>("link_og_id");

                    b.Property<string>("link_url");

                    b.Property<string>("messenger_sponsored_message");

                    b.Property<string>("name");

                    b.Property<long?>("object_id");

                    b.Property<string>("object_story_id");

                    b.Property<string>("object_type");

                    b.Property<string>("object_url");

                    b.Property<string>("status");

                    b.Property<string>("template_url");

                    b.Property<string>("thumbnail_url");

                    b.Property<string>("title");

                    b.Property<string>("url_tags");

                    b.Property<long?>("video_id");

                    b.HasKey("AppUserDataSyncId", "id");

                    b.ToTable("_AdCreativeHistory");
                });

            modelBuilder.Entity("Assassins.DataModels.LeadForms.LeadForm", b =>
                {
                    b.Property<long>("id");

                    b.Property<long>("AppUserDataSyncId");

                    b.Property<DateTime>("DateRecorded");

                    b.HasKey("id");

                    b.HasIndex("AppUserDataSyncId");

                    b.ToTable("LeadForms");
                });

            modelBuilder.Entity("Assassins.DataModels.Actions.CostPer10SecVideoView", b =>
                {
                    b.HasBaseType("Assassins.DataModels.Actions.Action");

                    b.HasDiscriminator().HasValue("CostPer10SecVideoView");
                });

            modelBuilder.Entity("Assassins.DataModels.Actions.CostPerActionType", b =>
                {
                    b.HasBaseType("Assassins.DataModels.Actions.Action");

                    b.HasDiscriminator().HasValue("CostPerActionType");
                });

            modelBuilder.Entity("Assassins.DataModels.Actions.CostPerThroughPlay", b =>
                {
                    b.HasBaseType("Assassins.DataModels.Actions.Action");

                    b.HasDiscriminator().HasValue("CostPerThroughPlay");
                });

            modelBuilder.Entity("Assassins.DataModels.Actions.CostPerUniqueActionType", b =>
                {
                    b.HasBaseType("Assassins.DataModels.Actions.Action");

                    b.HasDiscriminator().HasValue("CostPerUniqueActionType");
                });

            modelBuilder.Entity("Assassins.DataModels.Actions.UniqueAction", b =>
                {
                    b.HasBaseType("Assassins.DataModels.Actions.Action");

                    b.HasDiscriminator().HasValue("UniqueAction");
                });

            modelBuilder.Entity("Assassins.DataModels.Actions.Video10SecWatchedAction", b =>
                {
                    b.HasBaseType("Assassins.DataModels.Actions.Action");

                    b.HasDiscriminator().HasValue("Video10SecWatchedAction");
                });

            modelBuilder.Entity("Assassins.DataModels.Actions.Video30SecWatchedAction", b =>
                {
                    b.HasBaseType("Assassins.DataModels.Actions.Action");

                    b.HasDiscriminator().HasValue("Video30SecWatchedAction");
                });

            modelBuilder.Entity("Assassins.DataModels.Actions.VideoAvgPercentWatchedAction", b =>
                {
                    b.HasBaseType("Assassins.DataModels.Actions.Action");

                    b.HasDiscriminator().HasValue("VideoAvgPercentWatchedAction");
                });

            modelBuilder.Entity("Assassins.DataModels.Actions.VideoAvgTimeWatchedAction", b =>
                {
                    b.HasBaseType("Assassins.DataModels.Actions.Action");

                    b.HasDiscriminator().HasValue("VideoAvgTimeWatchedAction");
                });

            modelBuilder.Entity("Assassins.DataModels.Actions.VideoP100WatchedAction", b =>
                {
                    b.HasBaseType("Assassins.DataModels.Actions.Action");

                    b.HasDiscriminator().HasValue("VideoP100WatchedAction");
                });

            modelBuilder.Entity("Assassins.DataModels.Actions.VideoP25WatchedAction", b =>
                {
                    b.HasBaseType("Assassins.DataModels.Actions.Action");

                    b.HasDiscriminator().HasValue("VideoP25WatchedAction");
                });

            modelBuilder.Entity("Assassins.DataModels.Actions.VideoP50WatchedAction", b =>
                {
                    b.HasBaseType("Assassins.DataModels.Actions.Action");

                    b.HasDiscriminator().HasValue("VideoP50WatchedAction");
                });

            modelBuilder.Entity("Assassins.DataModels.Actions.VideoP75WatchedAction", b =>
                {
                    b.HasBaseType("Assassins.DataModels.Actions.Action");

                    b.HasDiscriminator().HasValue("VideoP75WatchedAction");
                });

            modelBuilder.Entity("Assassins.DataModels.Actions.VideoP95WatchedAction", b =>
                {
                    b.HasBaseType("Assassins.DataModels.Actions.Action");

                    b.HasDiscriminator().HasValue("VideoP95WatchedAction");
                });

            modelBuilder.Entity("Assassins.DataModels.Actions.VideoThruPlayWatchedAction", b =>
                {
                    b.HasBaseType("Assassins.DataModels.Actions.Action");

                    b.HasDiscriminator().HasValue("VideoThruPlayWatchedAction");
                });

            modelBuilder.Entity("Assassins.DataModels.Campaigns.WebsiteCtr", b =>
                {
                    b.HasBaseType("Assassins.DataModels.Actions.Action");

                    b.HasDiscriminator().HasValue("WebsiteCtr");
                });

            modelBuilder.Entity("Assassins.DataModels.Actions.Action", b =>
                {
                    b.HasOne("Assassins.DataModels.Actions.ActionType", "action_type")
                        .WithMany("Actions")
                        .HasForeignKey("action_type_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Assassins.DataModels.Campaigns.CampaignInsight", "CampaignInsight")
                        .WithMany("actions")
                        .HasForeignKey("campaign_insight_id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Assassins.DataModels.AdAccounts.AdAccount", b =>
                {
                    b.HasOne("Assassins.DataModels.AppUsers.AppUserDataSync", "AppUserDataSync")
                        .WithMany("AdAccounts")
                        .HasForeignKey("AppUserDataSyncId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Assassins.DataModels.AppUsers.AppUser", "AppUser")
                        .WithMany("AdAccounts")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Assassins.DataModels.AdAccounts.Business", "business")
                        .WithMany("AdAccounts")
                        .HasForeignKey("business_id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Assassins.DataModels.AdAccounts._AdAccountHistoryItem", b =>
                {
                    b.HasOne("Assassins.DataModels.AppUsers.AppUserDataSync", "AppUserDataSync")
                        .WithMany()
                        .HasForeignKey("AppUserDataSyncId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Assassins.DataModels.AppUsers.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Assassins.DataModels.AdAccounts.Business", "business")
                        .WithMany()
                        .HasForeignKey("businessid");
                });

            modelBuilder.Entity("Assassins.DataModels.AdImages.AdImage", b =>
                {
                    b.HasOne("Assassins.DataModels.AppUsers.AppUserDataSync", "AppUserDataSync")
                        .WithMany("AdImages")
                        .HasForeignKey("AppUserDataSyncId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Assassins.DataModels.AdImages._AdImageHistoryItem", b =>
                {
                    b.HasOne("Assassins.DataModels.AppUsers.AppUserDataSync", "AppUserDataSync")
                        .WithMany()
                        .HasForeignKey("AppUserDataSyncId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Assassins.DataModels.AdSets.AdSet", b =>
                {
                    b.HasOne("Assassins.DataModels.AppUsers.AppUserDataSync", "AppUserDataSync")
                        .WithMany("AdSets")
                        .HasForeignKey("AppUserDataSyncId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Assassins.DataModels.AdAccounts.AdAccount", "AdAccount")
                        .WithMany("adsets")
                        .HasForeignKey("account_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Assassins.DataModels.Campaigns.Campaign", "Campaign")
                        .WithMany("adsets")
                        .HasForeignKey("campaign_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Assassins.DataModels.AdSets.Targeting", "targeting")
                        .WithOne("AdSet")
                        .HasForeignKey("Assassins.DataModels.AdSets.AdSet", "id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Assassins.DataModels.AdSets.Geolocation", b =>
                {
                    b.HasOne("Assassins.DataModels.AppUsers.AppUserDataSync", "AppUserDataSync")
                        .WithMany()
                        .HasForeignKey("AppUserDataSyncId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Assassins.DataModels.AdSets.Targeting", "Targeting")
                        .WithOne("geo_locations")
                        .HasForeignKey("Assassins.DataModels.AdSets.Geolocation", "adset_id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Assassins.DataModels.AdSets.GeolocationRegionMap", b =>
                {
                    b.HasOne("Assassins.DataModels.AppUsers.AppUserDataSync", "AppUserDataSync")
                        .WithMany()
                        .HasForeignKey("AppUserDataSyncId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Assassins.DataModels.AdSets.Geolocation", "GeoLocation")
                        .WithMany("region_maps")
                        .HasForeignKey("adset_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Assassins.DataModels.AdSets.Region", "Region")
                        .WithMany("GeoLocationRegionMaps")
                        .HasForeignKey("key")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Assassins.DataModels.AdSets.Targeting", b =>
                {
                    b.HasOne("Assassins.DataModels.AppUsers.AppUserDataSync", "AppUserDataSync")
                        .WithMany()
                        .HasForeignKey("AppUserDataSyncId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Assassins.DataModels.AdSets._AdSetHistoryItem", b =>
                {
                    b.HasOne("Assassins.DataModels.AppUsers.AppUserDataSync", "AppUserDataSync")
                        .WithMany()
                        .HasForeignKey("AppUserDataSyncId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Assassins.DataModels.AdSets._GeolocationHistoryItem", b =>
                {
                    b.HasOne("Assassins.DataModels.AppUsers.AppUserDataSync", "AppUserDataSync")
                        .WithMany()
                        .HasForeignKey("AppUserDataSyncId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Assassins.DataModels.AdSets._GeolocationRegionMapHistoryItem", b =>
                {
                    b.HasOne("Assassins.DataModels.AppUsers.AppUserDataSync", "AppUserDataSync")
                        .WithMany()
                        .HasForeignKey("AppUserDataSyncId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Assassins.DataModels.AdSets._TargetingHistoryItem", b =>
                {
                    b.HasOne("Assassins.DataModels.AppUsers.AppUserDataSync", "AppUserDataSync")
                        .WithMany()
                        .HasForeignKey("AppUserDataSyncId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Assassins.DataModels.Ads.Ad", b =>
                {
                    b.HasOne("Assassins.DataModels.AppUsers.AppUserDataSync", "AppUserDataSync")
                        .WithMany("Ads")
                        .HasForeignKey("AppUserDataSyncId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Assassins.DataModels.AdAccounts.AdAccount", "AdAccount")
                        .WithMany("ads")
                        .HasForeignKey("account_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Assassins.DataModels.AdSets.AdSet", "AdSet")
                        .WithMany("Ads")
                        .HasForeignKey("adset_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Assassins.DataModels.Campaigns.Campaign", "Campaign")
                        .WithMany("ads")
                        .HasForeignKey("campaign_id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Assassins.DataModels.Ads._AdHistoryItem", b =>
                {
                    b.HasOne("Assassins.DataModels.AppUsers.AppUserDataSync", "AppUserDataSync")
                        .WithMany()
                        .HasForeignKey("AppUserDataSyncId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Assassins.DataModels.AppUsers.AppUserDataSync", b =>
                {
                    b.HasOne("Assassins.DataModels.AppUsers.AppUser", "AppUser")
                        .WithMany("DataSyncs")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Assassins.DataModels.AppUsers.AppUserRole", b =>
                {
                    b.HasOne("Assassins.DataModels.AppUsers.AppUser", "AppUser")
                        .WithMany("UserRoles")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Assassins.DataModels.AppUsers.AppRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Assassins.DataModels.Campaigns.Campaign", b =>
                {
                    b.HasOne("Assassins.DataModels.AppUsers.AppUserDataSync", "AppUserDataSync")
                        .WithMany("Campaigns")
                        .HasForeignKey("AppUserDataSyncId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Assassins.DataModels.AppUsers.AppUser", "AppUser")
                        .WithMany("Campaigns")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Assassins.DataModels.AdAccounts.AdAccount", "AdAccount")
                        .WithMany("campaigns")
                        .HasForeignKey("account_id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Assassins.DataModels.Campaigns.CampaignInsight", b =>
                {
                    b.HasOne("Assassins.DataModels.Campaigns.Campaign", "Campaign")
                        .WithMany("CampaignInsights")
                        .HasForeignKey("campaign_id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Assassins.DataModels.Campaigns._CampaignHistoryItem", b =>
                {
                    b.HasOne("Assassins.DataModels.AppUsers.AppUserDataSync", "AppUserDataSync")
                        .WithMany()
                        .HasForeignKey("AppUserDataSyncId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Assassins.DataModels.AppUsers.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Assassins.DataModels.Creatives.AdCreative", b =>
                {
                    b.HasOne("Assassins.DataModels.AdImages.AdImage", "AdImage")
                        .WithMany("AdCreatives")
                        .HasForeignKey("AdImageid");

                    b.HasOne("Assassins.DataModels.AppUsers.AppUserDataSync", "AppUserDataSync")
                        .WithMany("AdCreatives")
                        .HasForeignKey("AppUserDataSyncId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Assassins.DataModels.AdAccounts.AdAccount", "AdAccount")
                        .WithMany("adcreatives")
                        .HasForeignKey("account_id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Assassins.DataModels.Creatives._AdCreativeHistoryItem", b =>
                {
                    b.HasOne("Assassins.DataModels.AppUsers.AppUserDataSync", "AppUserDataSync")
                        .WithMany()
                        .HasForeignKey("AppUserDataSyncId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Assassins.DataModels.LeadForms.LeadForm", b =>
                {
                    b.HasOne("Assassins.DataModels.AppUsers.AppUserDataSync", "AppUserDataSync")
                        .WithMany("LeadForms")
                        .HasForeignKey("AppUserDataSyncId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
